steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' 
    args:
      - gcloud
      - functions
      - deploy
      - function_cicd
      - --region=us-central1
      - --source=.
      - --trigger-htpp
      - --runtime=python39
      - --allow-unauthenticated  
